services:
  - type: web
    name: mp3-url-tool
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mp3-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.10

databases:
  - name: mp3-db
    plan: free
